name: Empty Commit with Geek Joke

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  joke-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Ensure we checkout the main branch
          ref: main
          # Persist the GITHUB_TOKEN for pushing
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch a geek joke
        id: get_joke
        run: |
          joke=$(curl -s https://geek-jokes.sameerkumar.website/api?format=text)
          echo "JOKE<<EOF" >> $GITHUB_OUTPUT
          echo "$joke" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit empty with joke message
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Передаём сообщение через stdin — никаких проблем с разбиением на слова
          git commit --allow-empty -F - <<EOF
${{ steps.get_joke.outputs.JOKE }}
EOF
      
      - name: Push to main
        run: |
          git push origin main
        env:
          # Use GITHUB_TOKEN to authenticate the push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
